/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai;

/**
 *
 * @author hp
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        OnePlayer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TwoPlayers = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(770, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(530, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(530, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\AI\\src\\ai\\Images\\person (1).png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 80, 90));

        OnePlayer.setBackground(new java.awt.Color(94, 39, 11));
        OnePlayer.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        OnePlayer.setForeground(new java.awt.Color(255, 255, 255));
        OnePlayer.setText("One Player");
        OnePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnePlayerActionPerformed(evt);
            }
        });
        jPanel1.add(OnePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 240, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\AI\\src\\ai\\Images\\group.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 50, 50));

        TwoPlayers.setBackground(new java.awt.Color(102, 51, 0));
        TwoPlayers.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        TwoPlayers.setForeground(new java.awt.Color(255, 255, 255));
        TwoPlayers.setText("Two Players");
        TwoPlayers.setMaximumSize(new java.awt.Dimension(141, 37));
        TwoPlayers.setMinimumSize(new java.awt.Dimension(141, 37));
        TwoPlayers.setPreferredSize(new java.awt.Dimension(141, 37));
        TwoPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoPlayersActionPerformed(evt);
            }
        });
        jPanel1.add(TwoPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 240, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\AI\\src\\ai\\Images\\2.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TwoPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoPlayersActionPerformed
        // TODO add your handling code here:
       Frame1 TwoPlayer=new Frame1();
       TwoPlayer.setLocationRelativeTo(null);
        TwoPlayer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TwoPlayersActionPerformed

    private void OnePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnePlayerActionPerformed
        // TODO add your handling code here:
        Level level=new Level();
        level.setLocationRelativeTo(null);
        level.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OnePlayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OnePlayer;
    private javax.swing.JButton TwoPlayers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
